import { RESUME_DATA } from "./resumeData";

/**
 * Generates a clean, ATS-optimized plain text Markdown resume.
 */
export function generateMarkdownResume(): string {
  const r = RESUME_DATA;
  let md = `# ${r.name}\n`;
  md += `**${r.title}**\n`;
  md += `*${r.subtitle}*\n\n`;
  md += `**Email:** ${r.email} | **LinkedIn:** ${r.linkedin} | **Phone:** ${r.phone} | **Location:** ${r.location}\n\n`;
  md += `---\n\n`;
  
  md += `## Executive Summary\n\n${r.summary}\n\n`;
  
  md += `## Core Competencies & Specializations\n\n`;
  r.coreCompetencies.forEach((cat) => {
    md += `### ${cat.category}\n`;
    md += cat.skills.map((s) => `- ${s}`).join("\n") + "\n\n";
  });

  md += `## Professional Experience\n\n`;
  r.experience.forEach((exp) => {
    md += `### ${exp.role} — ${exp.organization}\n`;
    md += `*${exp.period} | ${exp.location}*\n\n`;
    exp.highlights.forEach((h) => {
      md += `- ${h}\n`;
    });
    md += `\n**Key Technologies:** ${exp.technologies.join(", ")}\n\n`;
  });

  md += `## Key Research Domains & Theoretical Syntheses\n\n`;
  r.researchDomains.forEach((dom) => {
    md += `### ${dom.domain}\n`;
    md += `**Focus Areas:**\n`;
    dom.keyThemes.forEach((th) => (md += `- ${th}\n`));
    md += `**Representative Works:** ${dom.representativePapers.join("; ")}\n\n`;
  });

  md += `## Selected Publications & Technical Briefs\n\n`;
  r.keyPublications.forEach((pub) => {
    md += `### ${pub.title}\n`;
    md += `*${pub.category}* ${pub.arxivLink ? `([arXiv Preprint](${pub.arxivLink}))` : ""}\n\n`;
    md += `${pub.impactSummary}\n\n`;
    md += `**Keywords:** ${pub.keywords.join(", ")}\n\n`;
  });

  md += `## Comprehensive Technical Keywords\n\n`;
  md += r.technicalKeywords.join(" • ") + "\n\n";
  
  md += `---\n*Generated by Meridian Journal · Scientific Resume Engine*\n`;
  return md;
}

/**
 * Generates an elegant, print-ready, high-resolution HTML document suitable for instant browser printing or PDF saving.
 */
export function generatePrintableHtmlResume(): string {
  const r = RESUME_DATA;
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${r.name} — Curriculum Vitae / Resume</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@600;700&family=JetBrains+Mono:wght@400;500;700&family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&display=swap');

    :root {
      --primary: #0a0a0a;
      --secondary: #404040;
      --accent: #0284c7;
      --accent-dark: #0369a1;
      --border: #e5e5e5;
      --bg: #ffffff;
      --tag-bg: #f5f5f5;
    }

    @page {
      margin: 15mm 15mm 15mm 15mm;
      size: A4 portrait;
    }

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      font-family: 'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      color: var(--primary);
      background-color: var(--bg);
      line-height: 1.55;
      font-size: 10pt;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    .resume-container {
      max-width: 820px;
      margin: 0 auto;
      padding: 30px;
    }

    header {
      border-bottom: 2px solid var(--primary);
      padding-bottom: 16px;
      margin-bottom: 20px;
    }

    .name-title {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      margin-bottom: 6px;
    }

    h1 {
      font-family: 'Cinzel', serif;
      font-size: 24pt;
      font-weight: 700;
      letter-spacing: -0.5px;
      color: #000;
      line-height: 1.1;
    }

    .lead-title {
      font-size: 11pt;
      font-weight: 700;
      color: var(--accent-dark);
      margin-bottom: 4px;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }

    .lead-subtitle {
      font-size: 9pt;
      color: var(--secondary);
      font-family: 'JetBrains Mono', monospace;
      margin-bottom: 10px;
    }

    .contact-grid {
      display: flex;
      flex-wrap: wrap;
      gap: 12px 18px;
      font-size: 8.5pt;
      font-family: 'JetBrains Mono', monospace;
      color: var(--secondary);
      background: #fafafa;
      padding: 8px 12px;
      border-radius: 6px;
      border: 1px solid var(--border);
    }

    .contact-item {
      display: flex;
      align-items: center;
      gap: 4px;
    }

    .contact-item a {
      color: var(--accent-dark);
      text-decoration: none;
      font-weight: 600;
    }

    section {
      margin-bottom: 20px;
    }

    h2 {
      font-family: 'Cinzel', serif;
      font-size: 11pt;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 1px;
      color: var(--primary);
      border-bottom: 1px solid var(--border);
      padding-bottom: 4px;
      margin-bottom: 12px;
      display: flex;
      align-items: center;
      justify-content: space-between;
    }

    .summary-text {
      font-size: 9.5pt;
      color: #333;
      text-align: justify;
      line-height: 1.6;
    }

    .grid-2col {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 16px;
    }

    .grid-3col {
      display: grid;
      grid-template-columns: 1fr 1fr 1fr;
      gap: 14px;
    }

    .comp-card {
      background: #fdfdfd;
      border: 1px solid var(--border);
      border-radius: 6px;
      padding: 10px 12px;
    }

    .comp-card h3 {
      font-size: 9pt;
      font-weight: 700;
      color: var(--accent-dark);
      margin-bottom: 6px;
      text-transform: uppercase;
      font-family: 'JetBrains Mono', monospace;
      border-bottom: 1px dashed var(--border);
      padding-bottom: 3px;
    }

    .comp-card ul {
      list-style-type: none;
      padding-left: 0;
    }

    .comp-card li {
      font-size: 8.5pt;
      margin-bottom: 3px;
      color: #444;
      display: flex;
      align-items: flex-start;
      gap: 5px;
    }

    .comp-card li::before {
      content: "▪";
      color: var(--accent);
      font-size: 8pt;
    }

    .exp-item {
      margin-bottom: 16px;
    }

    .exp-header {
      display: flex;
      justify-content: space-between;
      align-items: baseline;
      margin-bottom: 2px;
    }

    .exp-role {
      font-size: 10pt;
      font-weight: 700;
      color: #000;
    }

    .exp-org {
      font-size: 9.5pt;
      color: var(--accent-dark);
      font-weight: 600;
    }

    .exp-meta {
      font-family: 'JetBrains Mono', monospace;
      font-size: 8pt;
      color: #666;
    }

    .exp-bullets {
      padding-left: 14px;
      margin-top: 6px;
      margin-bottom: 6px;
    }

    .exp-bullets li {
      font-size: 9pt;
      color: #333;
      margin-bottom: 3px;
      line-height: 1.5;
    }

    .tech-pill-list {
      display: flex;
      flex-wrap: wrap;
      gap: 4px;
      margin-top: 4px;
    }

    .tech-pill {
      font-family: 'JetBrains Mono', monospace;
      font-size: 7pt;
      background: var(--tag-bg);
      border: 1px solid var(--border);
      padding: 1px 6px;
      border-radius: 4px;
      color: #555;
    }

    .pub-card {
      margin-bottom: 12px;
      padding: 8px 10px;
      background: #fafafa;
      border-left: 3px solid var(--accent);
      border-radius: 0 6px 6px 0;
    }

    .pub-title {
      font-size: 9pt;
      font-weight: 700;
      color: #000;
      margin-bottom: 2px;
    }

    .pub-meta {
      font-size: 7.5pt;
      font-family: 'JetBrains Mono', monospace;
      color: var(--secondary);
      margin-bottom: 4px;
    }

    .pub-desc {
      font-size: 8.5pt;
      color: #444;
      line-height: 1.45;
      margin-bottom: 4px;
    }

    .pub-tags {
      display: flex;
      flex-wrap: wrap;
      gap: 4px;
    }

    .keyword-cloud {
      display: flex;
      flex-wrap: wrap;
      gap: 5px;
    }

    .keyword-badge {
      font-family: 'JetBrains Mono', monospace;
      font-size: 7.5pt;
      background: #f0f9ff;
      color: #0369a1;
      border: 1px solid #bae6fd;
      padding: 2px 7px;
      border-radius: 4px;
    }

    footer {
      margin-top: 24px;
      border-top: 1px solid var(--border);
      padding-top: 10px;
      display: flex;
      justify-content: space-between;
      font-size: 7.5pt;
      color: #888;
      font-family: 'JetBrains Mono', monospace;
    }

    @media print {
      body {
        background: transparent;
      }
      .resume-container {
        padding: 0;
        max-width: 100%;
      }
      .no-print {
        display: none !important;
      }
    }
  </style>
</head>
<body>
  <div class="resume-container">
    <header>
      <div class="name-title">
        <div>
          <h1>${r.name}</h1>
          <div class="lead-title">${r.title}</div>
          <div class="lead-subtitle">${r.subtitle}</div>
        </div>
      </div>
      <div class="contact-grid">
        <div class="contact-item">📧 <a href="mailto:${r.email}">${r.email}</a></div>
        <div class="contact-item">💼 <a href="${r.linkedin}" target="_blank">linkedin.com/in/lucaskempe</a></div>
        <div class="contact-item">📞 ${r.phone}</div>
        <div class="contact-item">📍 ${r.location}</div>
      </div>
    </header>

    <section>
      <h2>Executive Summary</h2>
      <p class="summary-text">${r.summary}</p>
    </section>

    <section>
      <h2>Core Competencies &amp; Technical Specializations</h2>
      <div class="grid-3col">
        ${r.coreCompetencies
          .map(
            (c) => `
          <div class="comp-card">
            <h3>${c.category}</h3>
            <ul>
              ${c.skills.map((s) => `<li>${s}</li>`).join("")}
            </ul>
          </div>
        `
          )
          .join("")}
      </div>
    </section>

    <section>
      <h2>Professional Experience &amp; Leadership</h2>
      ${r.experience
        .map(
          (exp) => `
        <div class="exp-item">
          <div class="exp-header">
            <div>
              <span class="exp-role">${exp.role}</span> · <span class="exp-org">${exp.organization}</span>
            </div>
            <div class="exp-meta">${exp.period} | ${exp.location}</div>
          </div>
          <ul class="exp-bullets">
            ${exp.highlights.map((h) => `<li>${h}</li>`).join("")}
          </ul>
          <div class="tech-pill-list">
            ${exp.technologies.map((t) => `<span class="tech-pill">${t}</span>`).join("")}
          </div>
        </div>
      `
        )
        .join("")}
    </section>

    <section>
      <h2>Key Research Domains &amp; Theoretical Syntheses</h2>
      <div class="grid-3col">
        ${r.researchDomains
          .map(
            (d) => `
          <div class="comp-card">
            <h3>${d.domain}</h3>
            <ul>
              ${d.keyThemes.map((th) => `<li>${th}</li>`).join("")}
            </ul>
          </div>
        `
          )
          .join("")}
      </div>
    </section>

    <section>
      <h2>Selected Publications &amp; Technical Briefs</h2>
      ${r.keyPublications
        .map(
          (pub) => `
        <div class="pub-card">
          <div class="pub-title">${pub.title}</div>
          <div class="pub-meta">
            ${pub.category} ${pub.arxivLink ? `· <a href="${pub.arxivLink}" style="color:var(--accent-dark);">arXiv Preprint</a>` : ""}
          </div>
          <div class="pub-desc">${pub.impactSummary}</div>
          <div class="pub-tags">
            ${pub.keywords.map((kw) => `<span class="tech-pill">${kw}</span>`).join("")}
          </div>
        </div>
      `
        )
        .join("")}
    </section>

    <section>
      <h2>Primary Technical Keywords &amp; Index</h2>
      <div class="keyword-cloud">
        ${r.technicalKeywords.map((k) => `<span class="keyword-badge">${k}</span>`).join("")}
      </div>
    </section>

    <footer>
      <span>Meridian Journal · Research &amp; Engineering Resume</span>
      <span>Verified Origin: ${r.location}</span>
    </footer>
  </div>
</body>
</html>`;
}

/**
 * Triggers file download directly in browser.
 */
export function downloadFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Triggers clean print dialog formatted specifically for PDF saving.
 */
export function printResumeDocument() {
  const html = generatePrintableHtmlResume();
  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.open();
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 300);
  }
}
